const kachmirImages = [
  '/images/kachmir/06-chambre-complete.jpeg',
  '/images/kachmir/04-ensemble-armoire.jpeg',
  '/images/kachmir/05-ensemble-coiffeuse.jpeg',
  '/images/kachmir/02-lit-face.jpeg',
  '/images/kachmir/08-lit-coffre.jpeg',
  '/images/kachmir/01-armoire-ouverte.jpeg',
  '/images/kachmir/09-armoire-interieur.jpeg',
  '/images/kachmir/14-armoire-centrale.jpeg',
  '/images/kachmir/03-coiffeuse.jpeg',
  '/images/kachmir/13-coiffeuse-ouverte.jpeg',
  '/images/kachmir/12-coiffeuse-rangements.jpeg',
  '/images/kachmir/11-chevet.jpeg',
  '/images/kachmir/10-chevet-ouvert.jpeg',
  '/images/kachmir/07-eclairage.jpeg',
]

const armadaImages = [
  '/images/armada/04-chambre-complete.jpeg',
  '/images/armada/03-ensemble-armoire.jpeg',
  '/images/armada/02-ensemble-coiffeuse.jpeg',
  '/images/armada/17-lit-face.jpeg',
  '/images/armada/16-lit-angle.jpeg',
  '/images/armada/01-armoire-face.jpeg',
  '/images/armada/20-armoire-vitrines.jpeg',
  '/images/armada/19-armoire-penderie.jpeg',
  '/images/armada/18-armoire-etageres.jpeg',
  '/images/armada/15-coiffeuse-fermee.jpeg',
  '/images/armada/12-coiffeuse-ouverte.jpeg',
  '/images/armada/11-coiffeuse-tiroirs.jpeg',
  '/images/armada/13-coiffeuse-colonne.jpeg',
  '/images/armada/14-colonne-ouverte.jpeg',
  '/images/armada/05-chevet-en-place.jpeg',
  '/images/armada/09-chevet-face.jpeg',
  '/images/armada/06-chevet-tiroir.jpeg',
  '/images/armada/07-chevet-ouvert.jpeg',
  '/images/armada/08-chevet-double-rangement.jpeg',
  '/images/armada/10-chevet-armoire.jpeg',
]

const evoraImages = [
  '/images/evora/05-chambre-complete.jpeg',
  '/images/evora/11-ensemble-lit-armoire.jpeg',
  '/images/evora/10-ensemble-lit-coiffeuse.jpeg',
  '/images/evora/21-lit-face.jpeg',
  '/images/evora/02-armoire-fermee.jpeg',
  '/images/evora/08-armoire-face.jpeg',
  '/images/evora/06-armoire-ouverte-face.jpeg',
  '/images/evora/01-armoire-angle.jpeg',
  '/images/evora/18-armoire-angle-ouverte.jpeg',
  '/images/evora/19-armoire-droite-ouverte.jpeg',
  '/images/evora/20-armoire-detail.jpeg',
  '/images/evora/04-coiffeuse-face.jpeg',
  '/images/evora/03-coiffeuse-angle.jpeg',
  '/images/evora/12-coiffeuse-rangements.jpeg',
  '/images/evora/07-chevet-gauche.jpeg',
  '/images/evora/09-chevet-droit.jpeg',
  '/images/evora/13-chevet-face.jpeg',
  '/images/evora/14-chevet-detail.jpeg',
  '/images/evora/15-chevet-ouvert.jpeg',
  '/images/evora/16-chevet-ferme.jpeg',
  '/images/evora/17-chevet-double-ouvert.jpeg',
]

export const categories = [
  {
    id: 'chambres',
    name: 'Chambres complètes',
    eyebrow: 'Notre spécialité',
    description: 'Des ensembles coordonnés avec lit, rangements, chevets et coiffeuse.',
    image: kachmirImages[0],
  },
]

export const products = [
  {
    id: 'chambre-kachmir',
    name: 'Chambre Kachmir',
    category: 'chambres',
    label: 'Disponible sur devis',
    summary: 'Kachmir est une chambre complète au style contemporain, habillée de beige cachemire et structurée par des détails noirs. Son lit entièrement capitonné intègre un coffre de rangement, tandis que l’armoire vitrée et la colonne décorative sont mises en valeur par un éclairage intérieur.',
    images: kachmirImages,
    finishes: ['Beige cachemire', 'Détails noirs', 'Verre fumé'],
    includes: [
      'Lit double capitonné avec coffre',
      'Deux tables de chevet à tiroir',
      'Grande armoire avec portes vitrées',
      'Coiffeuse avec miroir rond',
      'Colonne vitrée avec éclairage',
      'Pouf assorti',
    ],
    details: [
      'Ensemble complet',
      'Lit avec coffre',
      'Éclairage intégré',
      'Livraison sur demande',
    ],
  },
  {
    id: 'chambre-armada',
    name: 'Chambre Armada',
    category: 'chambres',
    label: 'Disponible sur devis',
    summary: 'Armada est une chambre complète aux tons crème et gris, rehaussée par des détails brun foncé et dorés. Son lit capitonné est accompagné d’une large tête de lit avec éclairages intégrés. L’armoire associe quatre portes centrales à deux vitrines latérales éclairées, tandis que la coiffeuse offre plusieurs tiroirs et une colonne vitrée assortie.',
    images: armadaImages,
    finishes: ['Crème brillant', 'Tissu gris', 'Détails brun et doré'],
    includes: [
      'Lit double capitonné',
      'Large tête de lit avec éclairages',
      'Deux tables de chevet à tiroirs',
      'Grande armoire avec vitrines latérales',
      'Coiffeuse avec miroir éclairé',
      'Colonne vitrée et pouf assorti',
    ],
    details: [
      'Ensemble complet',
      'Tête de lit éclairée',
      'Nombreux rangements',
      'Livraison sur demande',
    ],
  },
  {
    id: 'chambre-evora',
    name: 'Chambre Evora',
    category: 'chambres',
    label: 'Disponible sur devis',
    summary: 'Evora est une chambre complète au style chaleureux, dominée par un bois brun foncé associé à des panneaux noirs et un capitonnage beige. Le lit présente une tête et un pied rembourrés, l’armoire offre de nombreux rangements avec un grand miroir central, et la coiffeuse réunit tiroirs, placards et miroir assorti.',
    images: evoraImages,
    finishes: ['Bois brun foncé', 'Panneaux noirs', 'Capitonnage beige'],
    includes: [
      'Lit double avec panneaux capitonnés',
      'Deux tables de chevet à deux tiroirs',
      'Grande armoire avec miroir central',
      'Rangements avec étagères et penderie',
      'Coiffeuse avec grand miroir',
      'Placards et tiroirs intégrés',
    ],
    details: [
      'Ensemble complet',
      'Grand miroir central',
      'Rangements généreux',
      'Livraison sur demande',
    ],
  },
]

export const kachmirFeatures = [
  {
    title: 'Lit capitonné avec coffre',
    text: 'Le cadre et la tête de lit sont entièrement rembourrés. Le sommier relevable donne accès à un grand espace de rangement sous le couchage.',
  },
  {
    title: 'Armoire vitrée éclairée',
    text: 'Une grande armoire avec penderie, étagères et tiroirs. Les portes centrales vitrées et les lignes lumineuses soulignent son design.',
  },
  {
    title: 'Coiffeuse et rangements',
    text: 'La coiffeuse réunit un miroir rond, plusieurs tiroirs compartimentés, un meuble latéral et une colonne vitrée assortie.',
  },
]
