export const categories = [
  {
    id: 'chambres',
    name: 'Chambres à coucher',
    eyebrow: 'Votre refuge personnel',
    description: 'Des ensembles complets où le calme, le rangement et la beauté trouvent naturellement leur place.',
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1600&q=85',
  },
  {
    id: 'lits',
    name: 'Lits & têtes de lit',
    eyebrow: 'La pièce maîtresse',
    description: 'Des lignes enveloppantes et des matières choisies pour transformer la chambre en véritable suite.',
    image: 'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?auto=format&fit=crop&w=1600&q=85',
  },
  {
    id: 'dressings',
    name: 'Dressings',
    eyebrow: 'L’ordre avec allure',
    description: 'Des rangements généreux, composés pour votre espace et pensés jusque dans les détails.',
    image: 'https://images.unsplash.com/photo-1616486338815-3dadae4b4ace?auto=format&fit=crop&w=1600&q=85',
  },
  {
    id: 'salons',
    name: 'Salons',
    eyebrow: 'Vivre ensemble',
    description: 'Des assises profondes et équilibrées, faites pour recevoir et durer.',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1600&q=85',
  },
]

export const products = [
  {
    id: 'suite-naya',
    name: 'Suite Naya',
    category: 'chambres',
    label: 'Nouvelle collection',
    summary: 'Une chambre complète aux volumes doux, soulignée par un bois chaud et des façades aux détails cannelés.',
    images: [
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1800&q=90',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1600&q=85',
    ],
    finishes: ['Chêne naturel', 'Noyer fumé', 'Beige sable'],
    includes: ['Lit double', 'Deux tables de chevet', 'Coiffeuse avec miroir', 'Armoire 6 portes'],
    details: ['Fabrication soignée', 'Rangements optimisés', 'Finitions personnalisables', 'Livraison disponible'],
  },
  {
    id: 'chambre-lyra',
    name: 'Chambre Lyra',
    category: 'chambres',
    label: 'Signature YZ',
    summary: 'Un jeu de courbes et de textures mates pour une atmosphère lumineuse, contemporaine et reposante.',
    images: [
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1800&q=90',
      'https://images.unsplash.com/photo-1615874694520-474822394e73?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=85',
    ],
    finishes: ['Blanc lin', 'Greige', 'Bois clair'],
    includes: ['Lit avec tête capitonnée', 'Deux chevets', 'Commode', 'Armoire avec miroir'],
    details: ['Tissu facile d’entretien', 'Charnières amorties', 'Éclairage en option', 'Montage professionnel'],
  },
  {
    id: 'lit-onda',
    name: 'Lit Onda',
    category: 'lits',
    label: 'Confort sculptural',
    summary: 'Une tête de lit panoramique et généreuse qui dessine une présence architecturale dans la chambre.',
    images: [
      'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?auto=format&fit=crop&w=1800&q=90',
      'https://images.unsplash.com/photo-1615874694520-474822394e73?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1600&q=85',
    ],
    finishes: ['Bouclé écru', 'Velours taupe', 'Tissu gris perle'],
    includes: ['Cadre de lit', 'Tête de lit panoramique', 'Sommier'],
    details: ['Plusieurs dimensions', 'Mousse haute densité', 'Structure renforcée', 'Tissus au choix'],
  },
  {
    id: 'lit-selene',
    name: 'Lit Sélène',
    category: 'lits',
    label: 'Douceur minimaliste',
    summary: 'Une silhouette basse et apaisante, équilibrée par une tête de lit rembourrée aux coutures graphiques.',
    images: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1800&q=90',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1600&q=85',
    ],
    finishes: ['Sable', 'Caramel', 'Graphite'],
    includes: ['Cadre de lit', 'Tête rembourrée', 'Sommier tapissier'],
    details: ['Angles adoucis', 'Textile résistant', 'Format sur mesure', 'Installation incluse selon zone'],
  },
  {
    id: 'dressing-aria',
    name: 'Dressing Aria',
    category: 'dressings',
    label: 'Sur mesure',
    summary: 'Une composition élégante, ouverte ou fermée, conçue autour de vos habitudes et de votre espace.',
    images: [
      'https://images.unsplash.com/photo-1558997519-83ea9252edf8?auto=format&fit=crop&w=1800&q=90',
      'https://images.unsplash.com/photo-1616486338815-3dadae4b4ace?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1611048267451-e6ed903d4a38?auto=format&fit=crop&w=1600&q=85',
    ],
    finishes: ['Bois naturel', 'Blanc mat', 'Verre fumé'],
    includes: ['Penderies', 'Étagères', 'Tiroirs', 'Accessoires intérieurs'],
    details: ['Étude personnalisée', 'Plans 3D', 'Éclairage LED en option', 'Pose professionnelle'],
  },
  {
    id: 'dressing-aura',
    name: 'Dressing Aura',
    category: 'dressings',
    label: 'Élégance utile',
    summary: 'Des façades pleine hauteur et des poignées intégrées pour un rangement parfaitement fondu dans la pièce.',
    images: [
      'https://images.unsplash.com/photo-1616486338815-3dadae4b4ace?auto=format&fit=crop&w=1800&q=90',
      'https://images.unsplash.com/photo-1558997519-83ea9252edf8?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1611048267451-e6ed903d4a38?auto=format&fit=crop&w=1600&q=85',
    ],
    finishes: ['Cachemire', 'Noyer', 'Blanc cassé'],
    includes: ['Modules au choix', 'Tiroirs amortis', 'Tringles', 'Étagères réglables'],
    details: ['Configuration libre', 'Mesure à domicile', 'Quincaillerie durable', 'Garantie atelier'],
  },
  {
    id: 'salon-alba',
    name: 'Salon Alba',
    category: 'salons',
    label: 'Best-seller',
    summary: 'Une assise profonde aux formes généreuses, conçue pour les grandes conversations et les longues soirées.',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1800&q=90',
      'https://images.unsplash.com/photo-1549187774-b4e9b0445b41?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1600&q=85',
    ],
    finishes: ['Bouclé crème', 'Vert olive', 'Taupe'],
    includes: ['Canapé 3 places', 'Canapé 2 places', 'Fauteuil'],
    details: ['Mousse haute résilience', 'Coussins déhoussables', 'Tissus au choix', 'Composition modulable'],
  },
  {
    id: 'salon-nova',
    name: 'Salon Nova',
    category: 'salons',
    label: 'Modulaire',
    summary: 'Un salon aux lignes nettes dont les modules s’adaptent aux espaces de vie contemporains.',
    images: [
      'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1800&q=90',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1549187774-b4e9b0445b41?auto=format&fit=crop&w=1600&q=85',
    ],
    finishes: ['Écru texturé', 'Gris pierre', 'Terracotta'],
    includes: ['Modules d’assise', 'Angle', 'Pouf'],
    details: ['Configuration personnalisée', 'Assise généreuse', 'Structure en bois', 'Large choix de textiles'],
  },
]

export const testimonials = [
  { name: 'Sara B.', city: 'Alger', text: 'La chambre est encore plus belle en vrai. Toute l’équipe a été attentive, du choix des finitions jusqu’au montage.' },
  { name: 'Amine K.', city: 'Blida', text: 'Le dressing a été parfaitement adapté à notre espace. Un résultat propre, élégant et vraiment fonctionnel.' },
  { name: 'Lina M.', city: 'Boumerdès', text: 'J’ai apprécié les conseils et la qualité des détails. On sent que chaque élément a été pensé avec soin.' },
]
